import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import HeroCard from "../components/HeroCard";
import TopMap from "../components/TopMap";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopMap />

      <div className="w-screen h-screen   backdrop-blur-lg">
        <HeroCard />
      </div>
    </div>
  );
};

export default Home;
